
#define LPSTR char far *

#define SZBUF_SIZE 80

#define ID_RESOURCE	  101

#define IDM_DDE 	  101

#define IDM_CREATE	  102
#define IDM_END 	  103
#define IDM_WRITE	  104
#define IDM_COMPOSE	  105
#define IDM_REPLY	  106

#define IDM_READ	  107
#define IDM_NUMBER	  108
#define IDM_AUTHOR	  109
#define IDM_PARENT	  110
#define IDM_CHILDREN	  111
#define IDM_DATE	  112
#define IDM_EXECUTE	  113
#define IDM_RUN 	  114
#define IDM_ENDCLIENT	  115
#define IDM_ENDSERVER	  116

#define IDM_SPAWN         117
#define IDM_EXCEL         118

#define IDM_OPTIONS       119
#define IDM_QUIET         120

#define IDD_CANCEL	  260
#define IDD_OK		  259
#define IDD_CRITEREA	  258
#define IDD_TEXT	  257

#define DID_GETVALUE	  256
